name: KIRA Script CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    - name: Lint kira_greet.sh
      run: shellcheck kira_greet.sh
